### ISSUE TITLE
How install it on rpi?

### ISSUE THREAD

**Issue by sogimu** [octohelm/harbor#429]
May you write some manual about?

**Comment by luckyluc74** [comment]
FYI this is how I installed harbor with `octohelm` arm 64 images on my rpi4 . Btw I am just a user of `octohelm` arm 64 images :) 


You need to have a working docker installed on your rpi4.
And also make sure you have following added to your `/boot/firmware/cmdline.txt` for docker
```
cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1
```

Get version v2.7.0 of harbor offline install and extract
```
wget https://github.com/goharbor/harbor/releases/download/v2.7.0/harbor-offline-installer-v2.7.0.tgz
tar xzvf harbor-offline-installer-v2.7.0.tgz
```

Go to extracted harbor directory
```
cd harbor
```

copy the harbor template yaml and customize it to your own need
```
cp harbor.yml.tmpl harbor.yml
```

I customized it like this
important: change 1.2.3.4 to your ip , https://yourdomain.com to your domain, and come up with your own password
```
/harbor# diff harbor.yml harbor.yml.tmpl
5c5
< hostname: 1.2.3.4
---
> hostname: reg.mydomain.com
17,18c17,18
<   certificate: /etc/docker/certs.d/1.2.3.4/ca.crt
<   private_key: /etc/docker/certs.d/1.2.3.4/ca.key
---
>   certificate: /your/certificate/path
>   private_key: /your/private/key/path
29c29
< external_url: https://yourdomain.com
---
> # external_url: https://reg.mydomain.com:8433
34c34
< harbor_admin_password: yourpassword
---
> harbor_admin_password: Harbor12345
39c39
<   password: yourpassword
---
>   password: root123

```

create certificate needed for harbor 
important: change to 1.2.3.4 to your own ip

Add follow lines to vi `/etc/ssl/openssl.cnf` needed for your local ca certifcate creation
```
# line 13
# This definition stops the following lines choking if HOME isn't
# defined.
RANDFILE                = $ENV::HOME/.rnd

# line 241
# PKIX recommendation.
subjectAltName = IP:1.2.3.4
```

create local ca certifcate and key for https
```
openssl req -newkey rsa:4096 -nodes -sha256 -keyout ca.key -x509 -days 3650 -out ca.crt
openssl req -newkey rsa:4096 -nodes -sha256 -keyout 1.2.3.4 -out 1.2.3.4
```

create temp file extfile.cnf 
```
vi extfile.cnf
```

and put following in this file
```
subjectAltName = IP:1.2.3.4
```

finish creation ca certificate and key
```
openssl x509 -req -days 3650 -in 1.2.3.4 -CA ca.crt -CAkey ca.key -CAcreateserial -extfile extfile.cnf -out 1.2.3.4
```
copy certificates
```
mkdir -p /etc/docker/certs.d/1.2.3.4
cp *.crt *.key /etc/docker/certs.d/1.2.3.4
```


create file `docker-compose.override.yml`  in your harbor directory
This override the images with arm64 images
```
version: '2.3'
services:
  log:
    image: ghcr.io/octohelm/harbor/harbor-log:v2.7.0
  registry:
    image: ghcr.io/octohelm/harbor/registry-photon:v2.7.0
  registryctl:
    image: ghcr.io/octohelm/harbor/harbor-registryctl:v2.7.0
  postgresql:
    image: ghcr.io/octohelm/harbor/harbor-db:v2.7.0
  core:
    image: ghcr.io/octohelm/harbor/harbor-core:v2.7.0
  portal:
    image: ghcr.io/octohelm/harbor/harbor-portal:v2.7.0
  jobservice:
    image: ghcr.io/octohelm/harbor/harbor-jobservice:v2.7.0
  redis:
    image: ghcr.io/octohelm/harbor/redis-photon:v2.7.0
  proxy:
    image: ghcr.io/octohelm/harbor/nginx-photon:v2.7.0
  trivy-adapter:
    image: ghcr.io/octohelm/harbor/trivy-adapter-photon:v2.7.0
```

then install harbor, in this example it is with trivy
```
./install.sh --with-trivy
```

And you have harbor 2.7.0 installed on your rpi4


Good luck!
